
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run: |
          sed -i "s/name=\"AuraMod\" version=\"CURRENT_VERSION\"/name=\"AuraMod\" version=\"${CIRCLE_TAG-0.0.$CIRCLE_BUILD_NUM}\"/" ./skin.auramod/addon.xml
          zip -Xr /tmp/skin.auramod.zip skin.auramod
      - store_artifacts:
          path: /tmp/skin.auramod.zip
      - persist_to_workspace:
          root: /tmp
          paths:
            - skin.auramod.zip
  release:
    parameters:
      commit_branch:
        type: string
        default: repo
      overwrite:
        type: boolean
        default: false
    docker:
      - image: circleci/python:2
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run: |
          git checkout << parameters.commit_branch >>
          python create_repository.py -d ./zips /tmp/skin.auramod.zip
          find ./zips -name "*.zip" | xargs python create_repository.py -d ./zips
      - unless:
          condition: << parameters.overwrite >>
          steps:
            run: git ls-files -m ./zips/|grep -v ".zip"
      - run: |
          git add ./zips
          git commit -m "Release version ${CIRCLE_TAG-0.0.$CIRCLE_BUILD_NUM}"
          git push
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - repo
      - release:
          context: publish
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
